[package]
name = "jsonrpc-ring-test"
version = "0.1.0"
authors = ["joe <anjone@126.com>"]
edition = "2018"

[dependencies]
failure = '0.1'
jsonrpc = '0.11.0'
jsonrpc-http-server = '11.0'
log = '0.4'
env_logger = '0.6'
serde = '1.0'
serde_derive = '1.0'
