apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k3s-app
  template:
    metadata:
      labels:
        app: k3s-app
    spec:
      containers:
      - name: k3s-app
        image: anjone/rpi-hostname:latest
---
apiVersion: v1
kind: Service
metadata:
  name: k3s-app
  namespace: default
spec:
  ports:
  - name: http
    targetPort: 8000
    port: 8000
  selector:
    app: k3s-app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k3s-app
  annotations:
    kubernetes.io/ingress.class: "traefik"

spec:
  rules:
  - host: k3s-app.example.org
    http:
      paths:
      - path: /
        backend:
          serviceName: k3s-app
          servicePort: http
