[package]
name = "redis-test"
version = "0.1.0"
authors = ["joe <anjone@126.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
failure = "0.1.5"
r2d2 = "0.8.4"
r2d2_redis = "0.9.0"
redis = "0.10.0"
