[package]
name = "prlib"
version = "0.1.0"
authors = ["joe <anjone@126.com>"]

[lib]
name = "prlib"
crate-type = ["dylib"]

[dependencies.cpython]
git = "https://github.com/dgrunwald/rust-cpython.git"
default-features = false
features = ["python3-sys"]