[package]
name = "hyper-test"
version = "0.1.0"
authors = ["joe <anjone@126.com>"]
edition = "2018"

[dependencies]
hyper = "0.11.7"
futures = "0.1.17"
net2 = "0.2.31"
tokio-core = "0.1.10"
num_cpus = "1.0"