[package]
name = "ctor-digest"
version = "0.1.0"
authors = ["joe <anjone@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "digest"
crate-type = ["staticlib"]

[dependencies]
libc = "*"
ring = "*"