[package]
name = "pg-users"
version = "0.1.0"
authors = ["joe <anjone@126.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
postgres = "0.15.2"
csv = "1.0.7"
failure = "0.1.5"
r2d2 = "0.8.4"
r2d2_postgres = "0.14.0"
rayon = "1.0.3"
serde = "1.0.90"
serde_derive = "1.0.90"
